@startuml

class User {
    - id: Int
    - name: String
    - email: String
    - password: String
}

class Event {
    - id: Int
    - title: String
    - background_image: String
    - category: Category
    - subcategory: SubCategory
    - description: String
    - event_start_date: Date
    - event_end_date: Date
    - location: Address
    - entry_fee: Float
    - host: User
    - IsPrivate: Boolean
}

class Category {
    -id: Int
    -name: String
    -subcategories: list<String>
}


class Subscription {
    -subscriber_id: user.id
    -subscribed_event_id: event.id
    -is_confirmed: Boolean
    -is_favorited: Boolean 
}

class Message {
    -id: Int
    -sender_id: Int
    -receiver_id: Int
    -content: String   
    -date: Date
}

class Thread {
    -comments: List<Comment>
}

class Comment {
    -id: Int
    -author_id: Int
    -event_id: Int
    -content: String
    -replies: List<Comment>
}

class Address {
    - country: String
    - state: String
    - city: String
    - zip_code: String
    - complement: String
}

class Chat {
    -participants: List<User>
    -messages: List<Message>
}

class Profile {
    -pic: String
    -created_at: Date
    -date_of_birth: Date
    -address: List<Address>
    -confirmed_events: List<Event>
    -favorited_events: List<Event>
}

class Notification {

}



User "0..*" --> "0..*" Event : performs
(User, Event) .. Subscription
User "1..*" --o "1" Chat
Chat "1" *-- "0..*" Message
User "1" --> "0..*" Comment: writes
Event "0..*" o-- "1" Category
Event "1"  *-- "1" Thread
Thread "1"  *-- "0..*" Comment
Comment "1" *-- "0..*" Comment
User "1" *-- "1" Profile


@enduml